### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by UnicornH** [a-r-j/graphein#44]
Dear 
I install all package and run the flow code:

from graphein.construct_graphs import ProteinGraph
from vmd import *
pg = ProteinGraph(granularity='CA', insertions=False, keep_hets=True,
                  node_featuriser='meiler', get_contacts_path='./getcontacts',
                  pdb_dir='examples/pdbs/',
                  contacts_dir='examples/contacts/',
                  exclude_waters=True, covalent_bonds=False, include_ss=True)

# Create residue-level graphs. Chain selection is either 'all' or a list e.g. ['A', 'B', 'D'] specifying the polypeptide chains to capture

# DGLGraph From PDB Accession Number
graph = pg.dgl_graph_from_pdb_code('3eiy', chain_selection='all')
# DGLGraph From PDB file
graph = pg.dgl_graph_from_pdb_file(file_path='examples/pdbs/pdb3eiy.pdb', contact_file='examples/contacts/3eiy_contacts.tsv', chain_selection='all')

# Create atom-level graphs
graph = pg._make_atom_graph(pdb_code='3eiy', graph_type='bigraph')
and I got these errors:
Traceback (most recent call last):
  File "./getcontacts/get_static_contacts.py", line 93, in <module>
    main()
  File "./getcontacts/get_static_contacts.py", line 80, in main
    ligand, solv, lipid, sele1, sele2)
  File "/home/jojo/PycharmProjects/PPI/getcontacts/contact_calc/compute_contacts.py", line 274, in compute_contacts
    output_fd = open(output, "w")
FileNotFoundError: [Errno 2] No such file or directory: 'examples/contacts/3eiy_contacts.tsv'

seems it couldn't computer contacts 
Could you please help me fix it?

**Comment by Seanny123** [comment]
The missing file, `examples/contacts/3eiy_contacts.tsv`, seems to exist on the `packaging` branch. You could checkout that branch to resolve your problem or you could checkout that specific file.
