### ISSUE TITLE
Pip Installation Trouble

### ISSUE THREAD

**Issue by chrisyeh96** [a-r-j/graphein#85]
It looks like there is some issue with how graphein's setup.py interacts with temporary files.

When I run `pip install graphein`, I get an error: 

```
$> pip install graphein
Collecting graphein==1.0.6
  Using cached graphein-1.0.6.tar.gz (102 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/cyeh/miniconda3/envs/mlprot/bin/python3.8 /home/cyeh/miniconda3/envs/mlprot/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_pr
ocess.py get_requires_for_build_wheel /tmp/tmpvrrujszc
       cwd: /tmp/pip-install-sh6rvu10/graphein_fa5f9d34ad2542e798361f4d27a1b533
  Complete output (24 lines):
  Traceback (most recent call last):
    File "/home/cyeh/miniconda3/envs/mlprot/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/cyeh/miniconda3/envs/mlprot/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/cyeh/miniconda3/envs/mlprot/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_whe
el
      return hook(config_settings)
    File "/tmp/pip-build-env-zrmcgwd7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-zrmcgwd7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-zrmcgwd7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-zrmcgwd7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 83, in <module>
      INSTALL_REQUIRES = read_requirements(".requirements/base.in")
    File "setup.py", line 59, in read_requirements
      for line in read(*parts).splitlines():
    File "setup.py", line 44, in read
      return codecs.open(os.path.join(HERE, *parts), "r").read()
    File "/home/cyeh/miniconda3/envs/mlprot/lib/python3.8/codecs.py", line 905, in open
      file = builtins.open(filename, mode, buffering)
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-sh6rvu10/graphein_fa5f9d34ad2542e798361f4d27a1b533/.requirements/base.in'
  ----------------------------------------
```

For context, I'm running `pip install graphein` inside a fresh conda environment create from the following environment (.yml) file:

```yml
name: mlprot
channels:
- pyg
- pytorch3d
- pytorch
- conda-forge
- anaconda
- bioconda
- plotly
- schrodinger
- salilab
dependencies:
- python=3.8
- biopython
- biopandas
- click
- cudatoolkit=10.2
- dssp
- flake8
- ipympl
- jupyterlab
- matplotlib
- multipledispatch
- mypy
- networkx
- nodejs
- numpy
- pandas
- pip
- plotly
- pydantic
- pyg
- pymol
- pyyaml
- pytorch
- pytorch3d
- scikit-learn
- scipy
- torchvision
- tqdm
- versioneer
- python-wget
- xarray
- pip:
  - bioservices
  - biovec
  - propy3
  - pyaaisc
```

**Comment by a-r-j** [comment]
Hi @chrisyeh96 thanks for pointing this out! Can't believe I didn't spot it. The requirements files weren't included in the `MANIFEST.in`. Should be good to go now - you can try with the latest version up on PyPI (`1.0.8`).

Let me know if the issue persists & feel free to reopen if so.

**Comment by chrisyeh96** [comment]
I can confirm that `pip install graphein==1.0.8` now works as expected. Thanks @a-r-j for the quick fix!
